### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SuperbSonik** [JPCERTCC/MalConfScan#11]
Dear all,

I am currently using Volatility 2.6.1 on Window10x64 and I am having an issues regarding to syntax error as shown below when I am doing malware analysis on a particular memory image: 
![Capture](https://user-images.githubusercontent.com/61529488/75409616-36383680-5954-11ea-9d14-4737d9b63ca7.PNG)

I tried to go to see the yara rules file syntax 227 and this is what it shown: 
![image](https://user-images.githubusercontent.com/61529488/75409693-6b448900-5954-11ea-9a99-b2076ed528a6.png)

and I delete the whole plugX coding and re-run command and this is what i get:
![image](https://user-images.githubusercontent.com/61529488/75409720-844d3a00-5954-11ea-9136-a5a63c16adf3.png)

this is my python version:
![image](https://user-images.githubusercontent.com/61529488/75409758-962edd00-5954-11ea-9799-917834c9ddbc.png)

Thank you if anyone is willing to give me some ideas :) appreciate it! have a nice day!

**Comment by shu-tom** [comment]
What version of Yara are you using?
