### ISSUE TITLE
Wrong path for plugins folder in latest release of Volatility (v2.6)

### ISSUE THREAD

**Issue by mopisec** [JPCERTCC/MalConfScan#16]
## Where to Fix

Following parts in wiki of this repository is wrong.

- https://github.com/JPCERTCC/MalConfScan/wiki/How-to-Install

![image](https://user-images.githubusercontent.com/41460213/107891083-d6211280-6f5f-11eb-9bf9-c33e5b786c48.png)

- https://github.com/JPCERTCC/MalConfScan/wiki/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

![image](https://user-images.githubusercontent.com/41460213/107891108-ee912d00-6f5f-11eb-9f86-6d4d0181b381.png)

## How to Fix

Before: `$ cp -R malconfscan.py utils yara [Extract Volatility Folder]/volatility/plugin/malware`
After: `$ cp -R malconfscan.py utils yara [Extract Volatility Folder]/volatility/plugins/malware`

## Evidence

![image](https://user-images.githubusercontent.com/41460213/107891144-27310680-6f60-11eb-8c6c-d346ee319eef.png)

**Comment by shu-tom** [comment]
Thank you. I fixed this typo.
