### ISSUE TITLE
how reliable is Emotet rule? (Emotet found in official GIMP installer)

### ISSUE THREAD

**Issue by inikishev** [JPCERTCC/MalConfScan#17]
https://www.gimp.org/downloads/ - GIMP 2.10.24 installer revision 3 for windows
https://www.virustotal.com/gui/file/5e9eabe5739523a9fc347b4614d919418f3335e7aab082a65f71705421e85e04/detection
does GIMP have emotet?
The reason I am asking is because emotet seems to be a very specific piece of malware and less likely to show a false positive

**Comment by shu-tom** [comment]
This is a false positive.
