### ISSUE TITLE
Only one extracted IP address is displayed because the key in the array is not updated

### ISSUE THREAD

**Issue by soji256** [JPCERTCC/MalConfScan#3]
The array index "i" is not incremented.

https://github.com/JPCERTCC/MalConfScan/blob/24516e53a2fcafdcfd9a2c40cd1776dcae628336/utils/emotetscan.py#L117

Therefore, only one IP address is displayed.

**Comment by shu-tom** [comment]
Thanks for adding issue. I fixed it.

**Comment by soji256** [comment]
It worked. Thanks for the quick fix!
