### ISSUE TITLE
Problem with ursnifscan

### ISSUE THREAD

**Issue by serosero** [JPCERTCC/MalConfScan#4]
I tried MalConfScan-with-Cuckoo with the sample page ursnif.
SHA256: 0207c06879fb4a2ddaffecc3a6713f2605cbdd90fc238da9845e88ff6aef3f85
But, I am troubled with an error.

  File "/home/name/venv/local/lib/python2.7/site-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/malware/utils/ursnifscan.py", line 245, in calculate
    parse_joinned_data(fname, magic)
NameError: global name 'parse_joinned_data' is not defined

**Comment by shu-tom** [comment]
I have fixed the bug, please retry.

**Comment by serosero** [comment]
Thanks for the quick fix! It's working.
