### ISSUE TITLE
volatility getting killed when running malconfscan

### ISSUE THREAD

**Issue by omrirefaeli** [JPCERTCC/MalConfScan#6]
installed and used exactly as shown.
`vol.py -f <path>.vmem --profile=Win7SP1x64 malconfscan`
5 seconds later getting the output:
```
[+] Searching memory by Yara rules.
Killed
```
and then it stops. same with malstrscan.
any solutions?

**Comment by shu-tom** [comment]
Is this a message from OOM Killer? Is this issue out of memory?

**Comment by omrirefaeli** [comment]
A reboot fixed it, probably something happened in my machine, unrelated to malconfscan
thanks.
